-- Supabase schema for personal portfolio

create extension if not exists pgcrypto;

create table if not exists public.site_settings (
  id bigint primary key generated by default as identity,
  name text not null,
  intro text not null,
  about text not null,
  email text not null,
  phone text not null,
  location text not null,
  profile_image text,
  instagram_url text,
  github_url text,
  linkedin_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.education (
  id bigint primary key generated by default as identity,
  institution text not null,
  degree text not null,
  year_start int not null,
  year_end int,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.experience (
  id bigint primary key generated by default as identity,
  company text not null,
  role text not null,
  year_start int not null,
  year_end int,
  location text,
  description text,
  logo_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint primary key generated by default as identity,
  title text not null,
  summary text not null,
  description text not null,
  tech_stack text[] not null default '{}',
  images text[] not null default '{}',
  live_url text,
  github_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.certificates (
  id bigint primary key generated by default as identity,
  title text not null,
  summary text not null,
  description text not null,
  image_url text,
  certificate_url text,
  issued_by text,
  issued_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.skills (
  id bigint primary key generated by default as identity,
  title text not null,
  icon text,
  knowledge_percent int,
  summary text not null,
  details text,
  tools text[] not null default '{}',
  project_ids text[] not null default '{}',
  display_order int,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint primary key generated by default as identity,
  name text not null,
  email text not null,
  phone text not null,
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_site_settings_updated_at on public.site_settings;
create trigger trg_site_settings_updated_at
before update on public.site_settings
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_projects_updated_at on public.projects;
create trigger trg_projects_updated_at
before update on public.projects
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_certificates_updated_at on public.certificates;
create trigger trg_certificates_updated_at
before update on public.certificates
for each row execute procedure public.set_updated_at();

insert into public.site_settings
  (id, name, intro, about, email, phone, location)
values
  (1, 'Your Name', 'I build modern web apps.', 'Write your detailed about section here.', 'youremail@gmail.com', '+91 00000 00000', 'Your City, Country')
on conflict (id) do nothing;

alter table public.site_settings enable row level security;
alter table public.education enable row level security;
alter table public.experience enable row level security;
alter table public.projects enable row level security;
alter table public.certificates enable row level security;
alter table public.messages enable row level security;

-- Public read policies for portfolio content
drop policy if exists "Public read site settings" on public.site_settings;
create policy "Public read site settings"
on public.site_settings
for select
to anon, authenticated
using (true);

drop policy if exists "Public read education" on public.education;
create policy "Public read education"
on public.education
for select
to anon, authenticated
using (true);

drop policy if exists "Public read experience" on public.experience;
create policy "Public read experience"
on public.experience
for select
to anon, authenticated
using (true);

drop policy if exists "Public read projects" on public.projects;
create policy "Public read projects"
on public.projects
for select
to anon, authenticated
using (true);

drop policy if exists "Public read certificates" on public.certificates;
create policy "Public read certificates"
on public.certificates
for select
to anon, authenticated
using (true);

-- Public can submit contact form
drop policy if exists "Public insert messages" on public.messages;
create policy "Public insert messages"
on public.messages
for insert
to anon, authenticated
with check (true);

-- Authenticated admin write policies
drop policy if exists "Admin manage site settings" on public.site_settings;
create policy "Admin manage site settings"
on public.site_settings
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Admin manage education" on public.education;
create policy "Admin manage education"
on public.education
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Admin manage experience" on public.experience;
create policy "Admin manage experience"
on public.experience
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Admin manage projects" on public.projects;
create policy "Admin manage projects"
on public.projects
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Admin manage certificates" on public.certificates;
create policy "Admin manage certificates"
on public.certificates
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Admin read messages" on public.messages;
create policy "Admin read messages"
on public.messages
for select
to authenticated
using (true);

drop policy if exists "Admin manage messages" on public.messages;
create policy "Admin manage messages"
on public.messages
for all
to authenticated
using (true)
with check (true);

-- Supabase storage bucket and policies
insert into storage.buckets (id, name, public)
values ('portfolio', 'portfolio', true)
on conflict (id) do nothing;

drop policy if exists "Public view portfolio images" on storage.objects;
create policy "Public view portfolio images"
on storage.objects
for select
to public
using (bucket_id = 'portfolio');

drop policy if exists "Authenticated upload portfolio images" on storage.objects;
create policy "Authenticated upload portfolio images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'portfolio');

drop policy if exists "Authenticated update portfolio images" on storage.objects;
create policy "Authenticated update portfolio images"
on storage.objects
for update
to authenticated
using (bucket_id = 'portfolio')
with check (bucket_id = 'portfolio');

drop policy if exists "Authenticated delete portfolio images" on storage.objects;
create policy "Authenticated delete portfolio images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'portfolio');

-- Auth repair (run only if login shows "Database error querying schema")
-- 1) Replace admin@portfolio.com with your admin email.
-- 2) Run this block once to remove broken auth rows for that email.
-- 3) Create the user from Supabase Dashboard -> Authentication -> Users -> Add user.
do $$
declare
  admin_user_id uuid;
  admin_email text := 'admin@portfolio.com';
begin
  select id into admin_user_id
  from auth.users
  where email = admin_email;

  if admin_user_id is not null then
    delete from auth.identities where user_id = admin_user_id;
    delete from auth.users where id = admin_user_id;
  end if;
end
$$;
